-- =====================================================
-- Add Your Custom Fonts to Database
-- =====================================================
-- Run this SQL in phpMyAdmin to add your uploaded custom fonts

-- Clear any existing sample data (optional)
DELETE FROM custom_fonts WHERE font_file_path LIKE '/admin/assets/fonts/custom/inter-%' 
   OR font_file_path LIKE '/admin/assets/fonts/custom/roboto-%';

-- Add your custom fonts
INSERT INTO custom_fonts 
(font_name, font_family, font_file_path, font_format, file_size, is_active, uploaded_date) 
VALUES 
-- All Formal by Kestrel Montes (Regular)
('All Formal Regular', 'All Formal', '/admin/assets/fonts/custom/All Formal by Kestrel Montes.otf', 'otf', 59956, 1, NOW()),

-- All Formal by Kestrel Montes (Italic)
('All Formal Italic', 'All Formal', '/admin/assets/fonts/custom/All Formal by Kestrel Montes Italic.otf', 'otf', 59752, 1, NOW()),

-- BesottedLove
('Besotted Love', 'Besotted Love', '/admin/assets/fonts/custom/BesottedLove.otf', 'otf', 112040, 1, NOW()),

-- Calgary Regular
('Calgary Regular', 'Calgary', '/admin/assets/fonts/custom/Calgary-Regular.otf', 'otf', 27792, 1, NOW());

-- =====================================================
-- Verify the fonts were added
-- =====================================================
-- Run this to see your fonts in the database:
-- SELECT font_name, font_family, font_file_path, is_active FROM custom_fonts WHERE is_active = 1 ORDER BY font_family, font_name;

-- =====================================================
-- CSS @font-face rules (for reference)
-- =====================================================
-- These will be automatically generated by the system, but here's what they look like:

/*
@font-face {
    font-family: 'All Formal';
    src: url('/admin/assets/fonts/custom/All Formal by Kestrel Montes.otf') format('opentype');
    font-weight: 400;
    font-style: normal;
    font-display: swap;
}

@font-face {
    font-family: 'All Formal';
    src: url('/admin/assets/fonts/custom/All Formal by Kestrel Montes Italic.otf') format('opentype');
    font-weight: 400;
    font-style: italic;
    font-display: swap;
}

@font-face {
    font-family: 'Besotted Love';
    src: url('/admin/assets/fonts/custom/BesottedLove.otf') format('opentype');
    font-weight: 400;
    font-style: normal;
    font-display: swap;
}

@font-face {
    font-family: 'Calgary';
    src: url('/admin/assets/fonts/custom/Calgary-Regular.otf') format('opentype');
    font-weight: 400;
    font-style: normal;
    font-display: swap;
}
*/
