@echo off
echo Starting workspace cleanup...

echo Moving documentation files...
move "ADMIN_SETTINGS_OVERHAUL_COMPLETION_REPORT.md" "ARCHIVE\documentation-md-files\"
move "AUTO_WRITE_PREVENTION_SUMMARY.md" "ARCHIVE\documentation-md-files\"
move "BLOG_INTEGRATION_PHASE1_COMPLETE.md" "ARCHIVE\documentation-md-files\"
move "BLOG_SYSTEM_COMPLETE_INTEGRATION_GUIDE.md" "ARCHIVE\documentation-md-files\"
move "BRACKET_FIXES_SUMMARY.md" "ARCHIVE\documentation-md-files\"
move "BRANDING_CLEANUP_SUMMARY.md" "ARCHIVE\documentation-md-files\"
move "BRANDING_ENHANCEMENT_SUMMARY.md" "ARCHIVE\documentation-md-files\"
move "BRANDING_SETTINGS_FIX.md" "ARCHIVE\documentation-md-files\"
move "BRANDING_SETTINGS_RESTORATION.md" "ARCHIVE\documentation-md-files\"
move "BRANDING_SYSTEM_IMPLEMENTATION.md" "ARCHIVE\documentation-md-files\"
move "BRANDING_SYSTEM_SETUP_GUIDE.md" "ARCHIVE\documentation-md-files\"
move "COMPLETE_SETTINGS_INTEGRATION_PLAN.md" "ARCHIVE\documentation-md-files\"
move "CONTACT_FORM_INTEGRATION_GUIDE.md" "ARCHIVE\documentation-md-files\"
move "CONTENT_TITLE_BLOCK_IMPLEMENTATION.md" "ARCHIVE\documentation-md-files\"
move "CONTENT_TITLE_BLOCK_ROLLOUT_PROGRESS.md" "ARCHIVE\documentation-md-files\"
move "CSS_JS_OPTIMIZATION_CHECKLIST_INTEGRATION.md" "ARCHIVE\documentation-md-files\"
move "CSS_JS_TABLE_STYLING_INTEGRATION_GUIDE.md" "ARCHIVE\documentation-md-files\"
move "CSS_NAVIGATION_FIXES_SUMMARY.md" "ARCHIVE\documentation-md-files\"
move "CSS_OPTIMIZATION_ANALYSIS.md" "ARCHIVE\documentation-md-files\"
move "CSS_OPTIMIZATION_INTEGRATION_PLAN.md" "ARCHIVE\documentation-md-files\"
move "DATABASE_SCHEMA_CORRECTIONS.md" "ARCHIVE\documentation-md-files\"
move "DATABASE_SCHEMA_FOR_ADMIN_FORMS.md" "ARCHIVE\documentation-md-files\"
move "DATABASE_SETTINGS_IMPLEMENTATION_GUIDE.md" "ARCHIVE\documentation-md-files\"
move "ENHANCED_FORMS_REQUIREMENTS_REMOVED.md" "ARCHIVE\documentation-md-files\"
move "GALLERY_DASHBOARD_ERROR_FIX.md" "ARCHIVE\documentation-md-files\"
move "GALLERY_DASHBOARD_STYLING_FIX.md" "ARCHIVE\documentation-md-files\"
move "GALLERY_INTEGRATION_PROGRESS_UPDATE.md" "ARCHIVE\documentation-md-files\"
move "GALLERY_INTEGRATION_STATUS.md" "ARCHIVE\documentation-md-files\"
move "GALLERY_PHP_UPDATE_GUIDE.md" "ARCHIVE\documentation-md-files\"
move "GALLERY_SYSTEM_INTEGRATION_COMPLETE.md" "ARCHIVE\documentation-md-files\"
move "INTEGRATION_COMPLETE_SUMMARY.md" "ARCHIVE\documentation-md-files\"
move "INTEGRATION_RESTRUCTURE_SUMMARY.md" "ARCHIVE\documentation-md-files\"
move "INVOICE_SYSTEM_MODERNIZATION_COMPLETE.md" "ARCHIVE\documentation-md-files\"
move "NAVIGATION_GUIDE.md" "ARCHIVE\documentation-md-files\"
move "NAVIGATION_PARAMETER_REFERENCE.md" "ARCHIVE\documentation-md-files\"
move "PHASE_2_CONTENT_ENHANCEMENT_GUIDE.md" "ARCHIVE\documentation-md-files\"
move "PROFESSIONAL_SETTINGS_ARCHITECTURE.md" "ARCHIVE\documentation-md-files\"
move "PROFESSIONAL_SETTINGS_ARCHITECTURE_COMPLETE.md" "ARCHIVE\documentation-md-files\"
move "PUBLIC_SETTINGS_FIX.md" "ARCHIVE\documentation-md-files\"
move "REVIEW_SYSTEM_EMERGENCY_RESTORATION.md" "ARCHIVE\documentation-md-files\"
move "SETTINGS_CLEANUP_SUMMARY.md" "ARCHIVE\documentation-md-files\"
move "SETTINGS_DASHBOARD_ORGANIZATION.md" "ARCHIVE\documentation-md-files\"
move "SETTINGS_DASHBOARD_SYSTEM_COMPLETE.md" "ARCHIVE\documentation-md-files\"
move "SETTINGS_IMPLEMENTATION_COMPLETE.md" "ARCHIVE\documentation-md-files\"
move "SETTINGS_SYSTEM_ANALYSIS.md" "ARCHIVE\documentation-md-files\"
move "SHOP_INTEGRATION_STEP1_COMPLETE.md" "ARCHIVE\documentation-md-files\"
move "SHOP_SYSTEM_INTEGRATION_PHASE2B_COMPLETE.md" "ARCHIVE\documentation-md-files\"
move "SHOP_SYSTEM_INTEGRATION_SUMMARY.md" "ARCHIVE\documentation-md-files\"
move "TEAM_REDESIGN_SUMMARY.md" "ARCHIVE\documentation-md-files\"
move "TICKET_SYSTEM_INTEGRATION_SUMMARY.md" "ARCHIVE\documentation-md-files\"
move "UNDEFINED_ARRAY_KEY_FIXES.md" "ARCHIVE\documentation-md-files\"
move "VARIABLE_FIXES_SUMMARY.md" "ARCHIVE\documentation-md-files\"
move "variable_mapping_summary.md" "ARCHIVE\documentation-md-files\"

echo Moving debug and test files...
move "analyze_fonts.php" "ARCHIVE\debug-test-files\"
move "check_about_fields.php" "ARCHIVE\debug-test-files\"
move "check_branding_table.php" "ARCHIVE\debug-test-files\"
move "check_db_structure.php" "ARCHIVE\debug-test-files\"
move "check_missing_vars.php" "ARCHIVE\debug-test-files\"
move "check_table_structure.php" "ARCHIVE\debug-test-files\"
move "check_team_pricing_tables.php" "ARCHIVE\debug-test-files\"
move "check_testimonials.php" "ARCHIVE\debug-test-files\"
move "database_content_mapping.php" "ARCHIVE\debug-test-files\"
move "database_diagnostic.php" "ARCHIVE\debug-test-files\"
move "debug_database_variables.php" "ARCHIVE\debug-test-files\"
move "debug_footer_values.php" "ARCHIVE\debug-test-files\"
move "debug_homepage_content_update.php" "ARCHIVE\debug-test-files\"
move "debug_logo_files.php" "ARCHIVE\debug-test-files\"
move "debug_logo_path.php" "ARCHIVE\debug-test-files\"
move "debug_media.php" "ARCHIVE\debug-test-files\"
move "debug_team_data.php" "ARCHIVE\debug-test-files\"
move "quick_test.php" "ARCHIVE\debug-test-files\"
move "simple_test.php" "ARCHIVE\debug-test-files\"
move "template-testing.php" "ARCHIVE\debug-test-files\"
move "test_about_alt.php" "ARCHIVE\debug-test-files\"
move "test_database_loading.php" "ARCHIVE\debug-test-files\"
move "test_pdo_connection.php" "ARCHIVE\debug-test-files\"
move "test_testimonials.php" "ARCHIVE\debug-test-files\"
move "test_variables.php" "ARCHIVE\debug-test-files\"
move "what-is-left-clean.php" "ARCHIVE\debug-test-files\"
move "what-is-left.php" "ARCHIVE\debug-test-files\"
move "todo.php" "ARCHIVE\debug-test-files\"

echo Moving corrupt/empty files...
move "execute()" "ARCHIVE\empty-files\"
move "execute([2])" "ARCHIVE\empty-files\"
move "getMessage()" "ARCHIVE\empty-files\"

echo Cleanup complete!
pause
