<?php
// Your MySQL database hostname.
define('db_host','localhost');
// Your MySQL database username.
define('db_user','root');
// Your MySQL database password.
define('db_pass','');
// Your MySQL database name.
define('db_name','phpgallery_advanced');
// Your MySQL database charset.
define('db_charset','utf8mb4');
// The URL of your website with the trailing slash.
define('website_url','http://localhost/projects/phpgallery/advanced/');
// If enabled, the media popup modal will appear as opposed to being redirected to a new page.
define('media_popup',true);
// Media layout
// The layout of the media grid can be either "masonry" or "grid".
// List:masonry=Masonry,grid=Grid
define('media_layout','masonry');
// Automatically play video when hovered over.
define('media_autoplay',true);
// The number of media to display per page.
define('media_per_page',12);
/* Upload */
// If enabled, the image is compressed with a value lower than 100 and therefore the file size is reduced.
define('image_quality',100);
// If enabled, the media orientation will be corrected when selecting media on responsive devices.
define('correct_image_orientation',false);
// The ImageMagick PHP extension is required to convert SVG images to PNG images.
define('convert_svg_to_png',false);
// Strip EXIF data from images to reduce file size.
define('strip_exif_data',false);
// The max width for uploaded images (-1 = no max width).
define('image_max_width',-1);
// The max height for uploaded images (-1 = no max height).
define('image_max_height',-1);
// If enabled, thumbnails are autogenerated for images.
define('auto_generate_image_thumbnail',false);
// The max width for autogenerated thumbnails.
define('auto_generate_image_thumbnail_max_width',354);
// The max height for autogenerated thumbnails.
define('auto_generate_image_thumbnail_max_height',354);
// Image max filesize, measured in bytes (5MB default).
define('image_max_size',5000000);
// Audio max filesize, measured in bytes (20MB default).
define('audio_max_size',20000000);
// Video max filesize, measured in bytes (100MB default).
define('video_max_size',100000000);
// If enabled, uploaded media will be required for approval by an administrator.
define('approval_required',false);
// If enabled, the user must be authenticated to upload media files.
define('authentication_required',true);
// PHP global settings; you can either adjust the values below or edit them in the php.ini file
// Increase the max upload file size - if you're using cloudflare, the limit is 100MB
ini_set('post_max_size', '200M');
ini_set('upload_max_filesize', '200M');

// Uncomment the below to output all errors
// ini_set('log_errors', true);
// ini_set('error_log', 'error.log');
// ini_set('display_errors', 1);
// ini_set('display_startup_errors', 1);
// error_reporting(E_ALL);

?>